#NumPy Arrays

In [1]:
my_list = [1,2,3]

In [2]:
import numpy as np #importando a biblioteca numPy como np

In [3]:
arr = np.array(my_list) #incluindo o my_list no numPy na variável arr

In [4]:
arr

array([1, 2, 3])

In [5]:
my_mat =[[1,2,3],[4,5,6],[7,8,9]]

In [6]:
my_mat # sem np apresenta as arrays em uma unica linha

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [7]:
np.array(my_mat) # com np apresenta as arrays em linhas e colunas (duas dimensões)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

#.arange

In [8]:
np.arange(0,11) #.arrange gera uma array, o parametro denominado aqui é (começo,parar) lembrando que é contado em index

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.arange(0,11,2) #o terceiro parâmetro é o step, então é exibido valores de 2 em 2 (nesse exemplo), 

array([ 0,  2,  4,  6,  8, 10])

#.zeros e .ones

In [10]:
np.zeros(3) #array de 3 zeros na mesma linha

array([0., 0., 0.])

In [11]:
np.zeros((5,5)) #array dentro de uma tuple sendo assim, 5 linhas e 5 colunas

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [12]:
np.zeros((2,3)) #aqui contem 2 linhas e 3 colunas

array([[0., 0., 0.],
       [0., 0., 0.]])

In [13]:
np.ones(4) #do mesmo jeito com .zeros, o .ones vai apresentar valores de 1. no array

array([1., 1., 1., 1.])

In [14]:
np.ones((3,4)) #exemplo com tuple

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

#.linspace

In [15]:
np.linspace(0,5,10) #.linspace retorna valores espaçados de acordo o intervalo definido (começo, parar, posições). detalhe importante que tudo isso esta em uma unica linha

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [18]:
np.linspace(0,5,20) #mesmo exemplo, porem com 20 espaços na mesma linha (uma dimensão)

array([0.        , 0.26315789, 0.52631579, 0.78947368, 1.05263158,
       1.31578947, 1.57894737, 1.84210526, 2.10526316, 2.36842105,
       2.63157895, 2.89473684, 3.15789474, 3.42105263, 3.68421053,
       3.94736842, 4.21052632, 4.47368421, 4.73684211, 5.        ])

#.eye

In [19]:
np.eye(4) #o .eye retorna uma array 2D com 1 em diagonal e 0 nos lugares restantes

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

#.randon.rand, .randn e .randint

In [20]:
np.random.rand(5) #.random.rand() exibe números aleatórios dentro de uma array, (nesse caso, 5 valores aleatorios)

array([0.71403086, 0.27509949, 0.32670585, 0.91176165, 0.73707979])

In [21]:
np.random.rand(5,5) #numero de linhas e colunas

array([[0.13988031, 0.62246446, 0.98977841, 0.85176915, 0.83063526],
       [0.88066054, 0.82120444, 0.39316822, 0.14575651, 0.2641619 ],
       [0.67118055, 0.37614202, 0.49785711, 0.83808775, 0.25611558],
       [0.24244523, 0.58894091, 0.41138253, 0.91972444, 0.44918497],
       [0.16189911, 0.39489739, 0.64504349, 0.50216557, 0.76288562]])

In [23]:
np.random.randn(5) #.randn faz a distribuição normal

array([-0.89451109, -0.53491348,  0.04807459, -0.19041558,  2.40371735])

In [24]:
np.random.randn(4,4)#4 linhas, 4 colunas

array([[-0.48585169,  0.03092457, -1.8162043 ,  1.69284234],
       [ 1.55656809, -1.28629577,  1.63033787,  0.67286864],
       [-1.14360798,  0.23567675, -1.23235117,  0.62502687],
       [-0.3288725 ,  0.89475188,  0.67687181,  0.82013842]])

In [25]:
np.random.randint(1,100) #retorna um número entre 1~100 (nesse exemplo) inteiro 

51

In [26]:
np.random.randint(1,100,10) #aqui retona 10 números entre 1~100 na mesma linha

array([83, 12, 29, 88, 78, 32, 18, 49, 69, 95])

#exemplo

In [27]:
arr = np.arange(25)

In [30]:
arr #.arange entrega 25 números em sequência

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [31]:
ranarr = np.random.randint(0,50,10)

In [32]:
ranarr #.random.randint entrega números aleatórios com um começo e fim e pode especificar a quantidade de números que vão ser impressos

array([ 0, 36,  1,  5, 29,  5, 22, 30, 39,  9])

#.reshape

In [38]:
arr.reshape(5,5) #.reshape acrescenta colunas e linhas para valores determinados, porém, o número de elementos tem que preencher exatamente o número de linhas e colunas

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [39]:
arr.reshape(5,10) #aqui ocorre um erro pois temos apenas 25 números, então, é impossivel acrescentar 25 números em 5 linhas e 10 colunas

ValueError: cannot reshape array of size 25 into shape (5,10)

#.max e .min

In [40]:
ranarr

array([ 0, 36,  1,  5, 29,  5, 22, 30, 39,  9])

In [42]:
ranarr.max() #exibe o valor máximo do array

39

In [43]:
ranarr.min() #exibe o valor mínimo do array

0

#.argmax e .argmin

In [44]:
ranarr

array([ 0, 36,  1,  5, 29,  5, 22, 30, 39,  9])

In [45]:
ranarr.argmax() #aqui exibe em qual index está o valor máximo

8

In [46]:
ranarr.argmin() #aqui exibe em qual index está o valor mínimo

0

#shape

In [48]:
arr.shape #25 valores em uma unica linha

(25,)

In [49]:
arr = arr.reshape(5,5) #colocando os valores em 5 linhas e 5 colunas

In [50]:
arr.shape #com o reshape agora tem 5 valores em 5 linhas e colunas

(5, 5)

#.dtype

In [51]:
arr.dtype #data type objects, nesse caso é "int32" (32bit integers)

dtype('int32')

#detalhe

In [52]:
from numpy.random import randint #se você quiser, é possível importar apenas o método dentro da numpy

In [53]:
randint(2,10)

6