#Indexing e Selection

In [1]:
import numpy as np

In [2]:
arr = np.arange(0,11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr[8]

8

In [5]:
arr[1:5] #começa na index 1 e encerra na index 5

array([1, 2, 3, 4])

In [6]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [7]:
arr[:6] #começo sem valor, automaticamente começará na index 0

array([0, 1, 2, 3, 4, 5])

In [8]:
arr[5:] #final sem valor, automaticamente irá encerrar na última index

array([ 5,  6,  7,  8,  9, 10])

In [9]:
arr[0:5] = 100 # das index 0 ate  5, o valor será 100

In [10]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [11]:
arr = np.arange(0,11)

#Slice

In [12]:
slice_of_arr = arr[0:6] #a variavel slice recebe o valor da index 0 até 6 de arr (lembrando que tem mais index dentro de arr)

In [13]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [14]:
slice_of_arr[:] = 99 #começo e fim não especificado, então todas as index vão receber o valor 99

In [15]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [16]:
arr #apesar de ter pegado o valor da index 0 até 5 de arr para o slice_of_arr, arr também recebeu os valores de 99 em suas index 0 até 6

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [17]:
arr_copy = arr.copy() #cópia de array

In [18]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [19]:
arr_copy #foi feito uma cópia ddo arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [20]:
arr_copy[:] = 100

In [21]:
arr_copy #a cópia foi alterada

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [22]:
arr #o original mantem com o mesmo valor

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

#Indexing

In [24]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]]) #criando uma array com duas dimensões

In [25]:
arr_2d #exibindo as arrays 2d (linha e coluna)

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [27]:
arr_2d[0][0] #selecionando o valor da index da linha 0 e coluna 0 (double brackets ou colchetes duplo)

5

In [29]:
arr_2d [0,0] #selecionando o mesmo valor da index da linha 0 e coluna 0 mas com apenas um colchete (single bracket), esse é o uso recomendado

5

In [30]:
arr_2d[:2,1:] #retornar tudo, exceto a linha 2 : retornar a partir da coluna 1 até o resto [li:nha,col:una]

array([[10, 15],
       [25, 30]])

In [32]:
arr = np.arange(1,11)

In [35]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [36]:
arr > 5 #aqui retorna valores booleanos dentro do array de acordo o valor da index

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [37]:
bool_arr = arr > 5

In [38]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [39]:
arr[bool_arr] #exibindo apenas valores True que são maiores que 5 já que bool_arr tem o valor de arr > 5

array([ 6,  7,  8,  9, 10])

In [40]:
arr[arr>5] #mesma função do bool_arr

array([ 6,  7,  8,  9, 10])

In [41]:
arr[arr<3] #exibindo valores menor que 3

array([1, 2])

In [42]:
arr_2d = np.arange(50).reshape(5,10) # arrange adicionando 50 valores e reshape distribuindo valores em 5 linhas e 10 colunas

In [43]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [45]:
arr_2d[1:3,3:5] #[começa da linha 1 : encerra antes da linha 3, começa da coluna 3 : encerra antes da coluna 5]

array([[13, 14],
       [23, 24]])