#NumPy Operations


    - Array com Array
    - Array com Scalars
    - Universal Array Functions

#array com array

In [1]:
import numpy as np

In [2]:
arr = np.arange(0,11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr + arr #aqui os valores do arr está somando com ele mesmo

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [5]:
arr - arr #aqui subtraindo com ele mesmo

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [6]:
arr * arr #aqui multiplicando com ele mesmo

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

#array com escalares

In [7]:
arr + 100 #aqui está sendo adcionado + 100 aos valores dentro de arr

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [8]:
arr - 100 #aqui subtraindo 100 aos valores dentro de arr

array([-100,  -99,  -98,  -97,  -96,  -95,  -94,  -93,  -92,  -91,  -90])

In [9]:
arr * 100 #aqui multiplicando 100 aos valores dentro de arr


array([   0,  100,  200,  300,  400,  500,  600,  700,  800,  900, 1000])

In [10]:
arr / arr #como o primeiro elemento da index é 0, é impossivel dividir por zero qualquer valor

C:\Users\ygcar\AppData\Local\Temp\ipykernel_9860\882955150.py:1: RuntimeWarning: invalid value encountered in divide
  arr / arr #como o primeiro elemento da index é 0, é impossivel dividir por zero qualquer valor


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [11]:
1 / arr #seguindo o mesmo exemplo, não é possível dividir zero

C:\Users\ygcar\AppData\Local\Temp\ipykernel_9860\2461622830.py:1: RuntimeWarning: divide by zero encountered in divide
  1 / arr #seguindo o mesmo exemplo, não é possível dividir zero


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [12]:
arr ** 2 #eleva a 2 os valores de de arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

Universal Functions

In [13]:
np.sqrt(arr) #np.sqrt é uma função de raiz quadrada com o parâmetro arr

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [16]:
np.max(arr) #função de valor máximo com o parâmetro arr 

10

In [17]:
arr.max() #é a mesma função acima, mas arr recebendo direto a função .max

10

In [18]:
np.sin(arr) #np.sin é o seno da trigonometria

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])